# Generated by Django 3.2.3 on 2021-06-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='articles/default.jpg', upload_to='articles'),
        ),
    ]
